# Generated by Django 3.0.4 on 2020-03-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_MediosImpugnacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediosimpugnacion',
            name='tipo_medioImpugnacion',
            field=models.CharField(choices=[('Juicio administrativo', 'Juicio administrativo'), ('Juicio de amparo', 'Juicio de amparo')], default='Tipo', max_length=255),
        ),
    ]
