# Generated by Django 3.0.4 on 2020-03-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasdeApremio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_expediente', models.CharField(max_length=255, unique=True)),
                ('motivos', models.TextField(max_length=255)),
                ('SujetoObligado', models.CharField(max_length=255)),
                ('nombreCortoSo', models.CharField(max_length=255, null=True)),
                ('cantidad', models.IntegerField()),
                ('tipoMedida', models.CharField(max_length=255)),
                ('fechaEmision', models.DateField()),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
