# Generated by Django 3.0.4 on 2020-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Mapremio', '0002_auto_20200325_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='medidasdeapremio',
            name='no_expediente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
