# Generated by Django 3.0.4 on 2020-03-26 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_MediosImpugnacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resoluciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_expediente', models.CharField(max_length=255, unique=True)),
                ('fecha_resolucion', models.DateField()),
                ('puntos_resolucion', models.TextField(max_length=255)),
                ('sentido_resolucion', models.TextField(max_length=255)),
                ('multa', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medioImpugnacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_MediosImpugnacion.MediosImpugnacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
