# Generated by Django 3.0.4 on 2020-03-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Resoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resoluciones',
            name='multa',
            field=models.CharField(choices=[('No', 'No'), ('Si', 'Si')], max_length=10),
        ),
    ]
